stages:
  - build-xvm
  - build-installer
  - deploy
  - notify
  
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

build-xvm:
  stage: build-xvm
  script:
    - ./build.sh
  artifacts:
    paths:
      - ~output/
    expire_in: 1 week

build-installer:
  stage: build-installer
  script:
    - ./src/installer/build.sh
  needs:
    - job: build-xvm
      artifacts: true
  artifacts:
    paths:
      - ~output/installer/
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - ./build/ci_deploy.sh
  needs:
    - job: build-xvm
      artifacts: true
    - job: build-installer
      artifacts: true
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[no-deploy\]/
      when: never
    - when: always

notify-krcm:
  stage: notify
  script:
    - ./build/ci_notify_krcm.sh
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[no-deploy\]/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /\[no-notify\]/
      when: never
    - when: always

notify-telegram:
  stage: notify
  script:
    - ./build/ci_notify_telegram.sh
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[no-deploy\]/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /\[no-notify\]/
      when: never
    - when: always
